// Generated by scripts/leave_core.py from annual-leave/index.html: the Annual Leave page's own leave rules and
// data mapping, word for word, for the Hub assistant. Don't edit this file: change the page (the leave tool),
// rebuild it with scripts/sync-leave.py, and this is rebuilt with it.
const BOARDS = { req: '5105073088', alw: '5105073023', grp: '5105073015', clo: '5105073038', oth: '5105088856' };
const BOARD_NAMES = {
  req: 'FLR - Annual Leave Requests', alw: 'FLR - Leave Allowances', grp: 'FLR - Leave Groups',
  clo: 'FLR - Bank Holidays & Closures', oth: 'FLR - Other Leave',
};
const REQ = {
  employee: 'multi_selectfix3go54', dates: 'date_rangeguqisxa9', halfDay: 'single_select21isbzj',
  notes: 'long_textpqrma3pp', email: 'emaild5yyc8lj', override: 'numeric_mm7myxeb',
  decision: 'color_mm7m6q47', suggested: 'color_mm7ms2n8', allowanceCheck: 'color_mm7mch2p',
  groupCheck: 'color_mm7m1hvs', workingDays: 'numeric_mm7mhjwa', leftAfter: 'numeric_mm7m3hg',
  leaveGroup: 'text_mm7mb7d3', details: 'long_text_mm7mc2nk', staff: 'board_relation_mm7ms0ah',
  decidedOn: 'date_mm7me598', managersNote: 'long_text_mm7mxp13',
};
const ALW = {
  group: 'board_relation_mm7ms80n', allowance: 'numeric_mm7mkptt', shutdown: 'numeric_mm7m8qs9',
  carried: 'numeric_mm7m314', booked: 'numeric_mm7mnq70', pending: 'numeric_mm7mb56e', email: 'email_mm7mfw2y',
};
const GRP = { members: 'board_relation_mm7ms65q', maxOff: 'numeric_mm7m80jy', rules: 'long_text_mm7mjg7b' };
const CLO = { date: 'date_mm7mny6j', type: 'color_mm7m8tgx' };
// FLR - Leave Closures has bank holidays, the Jeff Day and company close days: the days FLR closes around Christmas,
// labelled "Christmas shutdown" on the board (either name is understood). The page calls each one a "Company close day".
const CLOSE_DAY = 'Company close day';
const isCloseDay = (type) => /shutdown|close day/i.test(type || '');
// The Notes column on the other-leave board is never loaded: it can hold health information.
const OTH = { dates: 'timerange_mm7mrm7g', halfDay: 'color_mm7mhgm1', workingDays: 'numeric_mm7mgar6', staff: 'board_relation_mm7mt3h4' };
const OTHER_GROUP_TYPES = {
  topics: 'Sick leave', group_mm7mmzt1: 'Unpaid leave', group_mm7mhhpx: 'Study leave',
  group_mm7mafk9: 'Compassionate leave', group_mm7mq37s: 'Medical appointment',
  group_mm7m3xrm: 'Maternity / paternity', group_mm7mazdm: 'TOIL',
};
const OTHER_TYPE_COLOURS = {
  'Sick leave': '#df2f4a', 'Unpaid leave': '#7f5347', 'Study leave': '#784bd1',
  'Compassionate leave': '#757575', 'Medical appointment': '#ff5ac4',
  'Maternity / paternity': '#66ccff', 'TOIL': '#cab641',
};
const PLACEHOLDER_NAMES = ['leave request', 'incoming form answer', 'new item'];

const FIRST_LEAVE_YEAR = 2027;
function toUTC(d) { const [y, m, day] = d.split('-').map(Number); return Date.UTC(y, m - 1, day); }
function fromUTC(ms) { return new Date(ms).toISOString().slice(0, 10); }
function addDays(d, n) { return fromUTC(toUTC(d) + n * 86400000); }
function weekday(d) { return new Date(toUTC(d)).getUTCDay(); }
function isWeekend(d) { const w = weekday(d); return w === 0 || w === 6; }
function yearOf(d) { return Number(d.slice(0, 4)); }
function cleanDate(v) {
  if (!v || typeof v !== 'string') return null;
  const m = v.match(/^(\d{4})-(\d{2})-(\d{2})/);
  return m ? `${m[1]}-${m[2]}-${m[3]}` : null;
}
function todayInLondon(now = new Date()) {
  const parts = new Intl.DateTimeFormat('en-GB', { timeZone: 'Europe/London', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(now);
  const get = (t) => parts.find((p) => p.type === t).value;
  return `${get('year')}-${get('month')}-${get('day')}`;
}
const DOW = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
function fmtDate(d, withYear = true) {
  const [y, m, day] = d.split('-').map(Number);
  return `${DOW[weekday(d)]} ${day} ${MON[m - 1]}${withYear ? ' ' + y : ''}`;
}
function fmtRange(from, to) {
  if (!from) return 'No dates';
  if (!to || to === from) return fmtDate(from);
  return `${fmtDate(from, yearOf(from) !== yearOf(to))} – ${fmtDate(to)}`;
}
function fmtNum(n) { const r = Math.round(n * 10) / 10; return Number.isInteger(r) ? String(r) : r.toFixed(1); }
function plural(n, word) { return `${fmtNum(n)} ${word}${n === 1 ? '' : 's'}`; }
function normaliseName(s) { return (s || '').toLowerCase().replace(/\s+/g, ' ').trim(); }
function decisionFromLabel(label) {
  switch ((label || '').trim().toLowerCase()) {
    case 'accepted': return 'accepted';
    case 'denied': return 'denied';
    case 'review': return 'review';
    case 'cancelled': return 'cancelled';
    default: return 'new';
  }
}
function halfDayFromLabel(label) {
  const l = (label || '').toLowerCase();
  if (l.includes('morning')) return 'am';
  if (l.includes('afternoon')) return 'pm';
  return 'none';
}
const isPending = (r) => r.decision === 'new' || r.decision === 'review';
const isActive = (r) => isPending(r) || r.decision === 'accepted';
function leaveDays(req, bankHolidays) {
  const out = { from: null, to: null, days: [], total: 0, byYear: {}, excluded: [], warnings: [], info: [] };
  let from = req.from || req.to;
  let to = req.to || req.from;
  if (!from) { out.warnings.push('No leave dates on the request.'); return out; }
  if (to < from) [from, to] = [to, from];
  out.from = from; out.to = to;
  for (let d = from; d <= to; d = addDays(d, 1)) {
    if (isWeekend(d)) continue;
    if (bankHolidays.has(d)) { out.excluded.push({ date: d, name: bankHolidays.get(d) }); continue; }
    out.days.push({ date: d, amount: 1 });
  }
  if (req.halfDay && req.halfDay !== 'none' && out.days.length > 0) {
    const label = req.halfDay === 'am' ? 'morning off' : 'afternoon off';
    if (out.days.length === 1) { out.days[0].amount = 0.5; out.info.push(`Half day (${label}).`); }
    else {
      out.days[out.days.length - 1].amount = 0.5;
      out.warnings.push(`Half day (${label}) was chosen on a multi-day request, so the last day is counted as a half day. Check the employee's notes.`);
    }
  }
  if (out.days.length === 0) out.warnings.push('The dates contain no working days (only weekends or bank holidays).');
  const override = req.daysOverride;
  if (override !== null && override !== undefined && override !== '' && !Number.isNaN(Number(override)) && Number(override) >= 0) {
    out.total = Number(override);
    out.byYear = { [yearOf(out.days[0] ? out.days[0].date : from)]: out.total };
    out.info.push(`Days override used: ${fmtNum(out.total)} days.`);
  } else {
    for (const { date, amount } of out.days) {
      out.total += amount;
      const y = yearOf(date);
      out.byYear[y] = (out.byYear[y] || 0) + amount;
    }
  }
  return out;
}
function buildContext({ requests, staff, groups, bankHolidays, today, otherLeave = [] }) {
  const staffById = new Map(staff.map((s) => [String(s.id), s]));
  const staffByName = new Map();
  for (const s of staff) { const key = normaliseName(s.name); if (key && !staffByName.has(key)) staffByName.set(key, s); }
  const groupById = new Map(groups.map((g) => [String(g.id), g]));
  const membersByGroup = new Map(groups.map((g) => [String(g.id), new Set((g.memberIds || []).map(String))]));
  const groupsByStaff = new Map(staff.map((s) => [String(s.id), new Set()]));
  for (const g of groups) for (const m of g.memberIds || []) if (groupsByStaff.has(String(m))) groupsByStaff.get(String(m)).add(String(g.id));
  for (const s of staff) {
    for (const gid of s.groupIds || []) {
      if (!groupById.has(String(gid))) continue;
      groupsByStaff.get(String(s.id)).add(String(gid));
      membersByGroup.get(String(gid)).add(String(s.id));
    }
  }
  const ctx = {
    requests, staff, groups, bankHolidays, today,
    currentYear: Math.max(yearOf(today), FIRST_LEAVE_YEAR),
    staffById, staffByName, groupById, membersByGroup, groupsByStaff, _days: new Map(),
  };
  ctx.daysOf = (r) => { if (!ctx._days.has(r.id)) ctx._days.set(r.id, leaveDays(r, bankHolidays)); return ctx._days.get(r.id); };
  ctx.staffOf = (r) => {
    if (r.staffId && staffById.has(String(r.staffId))) return staffById.get(String(r.staffId));
    return staffByName.get(normaliseName(r.employeeName)) || null;
  };
  ctx.groupsOf = (s) => (s ? [...(groupsByStaff.get(String(s.id)) || [])].map((id) => groupById.get(id)) : []);
  ctx.otherLeave = otherLeave;
  ctx._otherDays = new Map();
  ctx.otherDaysOf = (e) => {
    if (!ctx._otherDays.has(e.id)) ctx._otherDays.set(e.id, leaveDays({ ...e, daysOverride: null }, bankHolidays));
    return ctx._otherDays.get(e.id);
  };
  ctx.otherStaffOf = (e) => {
    if (e.staffId && staffById.has(String(e.staffId))) return staffById.get(String(e.staffId));
    return staffByName.get(normaliseName(e.employeeName)) || null;
  };
  return ctx;
}
function whoIsOffOther(ctx, date) {
  const out = [];
  if (isWeekend(date) || ctx.bankHolidays.has(date)) return out;
  for (const e of ctx.otherLeave) {
    const entry = ctx.otherDaysOf(e).days.find((x) => x.date === date);
    if (entry) out.push({ entry: e, staff: ctx.otherStaffOf(e), type: e.type, amount: entry.amount });
  }
  return out;
}
function otherTotalsFor(ctx, s, year) {
  const totals = {};
  for (const e of ctx.otherLeave) {
    const owner = ctx.otherStaffOf(e);
    if (!owner || String(owner.id) !== String(s.id)) continue;
    const n = ctx.otherDaysOf(e).byYear[year] || 0;
    if (n) totals[e.type] = (totals[e.type] || 0) + n;
  }
  return totals;
}
function maxOffOf(g) { const n = Number(g && g.maxOff); return Number.isFinite(n) && n >= 1 ? Math.floor(n) : 1; }
function balanceFor(ctx, s, year, excludeId = null) {
  const inCurrent = year === ctx.currentYear;
  const allowance = Number(s.allowance) || 0;
  const reserved = Number(s.shutdownReserve) || 0;
  const carried = inCurrent ? Number(s.carriedOver) || 0 : 0;
  const takenBefore = inCurrent ? Number(s.takenBefore) || 0 : 0;
  let booked = 0, pending = 0;
  for (const r of ctx.requests) {
    if (r.id === excludeId) continue;
    const owner = ctx.staffOf(r);
    if (!owner || String(owner.id) !== String(s.id)) continue;
    const n = ctx.daysOf(r).byYear[year] || 0;
    if (r.decision === 'accepted') booked += n; else if (isPending(r)) pending += n;
  }
  const entitlement = allowance - reserved + carried;
  const remaining = entitlement - takenBefore - booked;
  return {
    allowance, reserved, carried, takenBefore, booked, pending, entitlement,
    remaining, remainingIfPending: remaining - pending,
    allowanceMissing: s.allowance === null || s.allowance === undefined || s.allowance === '',
  };
}
function evaluateRequest(ctx, req) {
  const days = ctx.daysOf(req);
  const s = ctx.staffOf(req);
  const res = {
    requestId: req.id, staff: s, days, years: [], allowanceStatus: 'Not on allowance board',
    groupStatus: 'No group set', groups: [], clashDays: 0, clashWithAccepted: false,
    suggested: 'Review', reason: '', leftAfter: null, groupNames: '', details: '',
  };
  const lines = [];
  lines.push(`Dates: ${fmtRange(days.from, days.to)} = ${plural(days.total, 'working day')} (weekends, bank holidays and company close days not counted).`);
  if (days.excluded.length) lines.push(`Bank holidays and company close days not counted: ${days.excluded.map((e) => `${fmtDate(e.date)} (${e.name})`).join(', ')}.`);
  for (const i of days.info) lines.push(i);
  for (const w of days.warnings) lines.push(`Warning: ${w}`);
  if (days.from && days.from < ctx.today) lines.push('Note: these dates start in the past.');
  if (!s) {
    lines.push(`"${req.employeeName || '(no name)'}" was not found on the FLR - Leave Allowances board, so allowance and group checks could not run. Add them there (the name must match the form exactly).`);
    res.reason = 'Employee not found on the allowance board';
    lines.push(`Suggested: Review – ${res.reason}.`);
    res.details = lines.join('\n');
    return res;
  }
  let over = false;
  let preTracker = 0;
  const years = Object.keys(days.byYear).map(Number).sort();
  if (years.length === 0 && days.from) years.push(yearOf(days.from));
  for (const y of years) {
    if (y < FIRST_LEAVE_YEAR) { preTracker += days.byYear[y] || 0; continue; }
    const b = balanceFor(ctx, s, y, req.id);
    const thisReq = days.byYear[y] || 0;
    const leftAfter = b.remaining - thisReq;
    const leftIfPending = leftAfter - b.pending;
    res.years.push({ year: y, ...b, thisRequest: thisReq, leftAfter, leftIfPending });
    if (leftAfter < 0) over = true;
    let line = `Allowance ${y}: ${fmtNum(b.allowance)} days`;
    if (b.reserved) line += ` − ${fmtNum(b.reserved)} held for company close days`;
    if (b.carried) line += ` + ${fmtNum(b.carried)} carried over`;
    if (b.reserved || b.carried) line += ` = ${fmtNum(b.entitlement)} bookable`;
    line += `. Used: ${fmtNum(b.booked)} accepted`;
    if (b.takenBefore) line += ` + ${fmtNum(b.takenBefore)} taken before the tracker`;
    line += `. This request: ${fmtNum(thisReq)} → ${fmtNum(leftAfter)} left after this.`;
    if (b.pending) line += ` Other pending requests: ${fmtNum(b.pending)} days (${fmtNum(leftIfPending)} left if they are accepted too).`;
    if (b.allowanceMissing) line += ' (No annual allowance set on the allowance board – counted as 0.)';
    lines.push(line);
  }
  const startsBeforeTracker = Boolean(days.from && yearOf(days.from) < FIRST_LEAVE_YEAR);
  if (startsBeforeTracker) lines.push(`Note: ${plural(preTracker, 'day')} fall before the tracker starts on 1 Jan ${FIRST_LEAVE_YEAR}, so they are not checked against the allowance.`);
  const primary = res.years.find((y) => days.from && y.year === yearOf(days.days[0] ? days.days[0].date : days.from)) || res.years[0];
  res.leftAfter = primary ? primary.leftAfter : null;
  res.allowanceStatus = over ? 'Over allowance' : 'Within allowance';
  const groups = ctx.groupsOf(s).filter(Boolean).sort((a, b) => a.name.localeCompare(b.name));
  res.groupNames = groups.map((g) => g.name).join(', ');
  if (groups.length === 0) {
    res.groupStatus = 'No group set';
    lines.push('Leave group: none set, so clashes could not be checked. Add this person to a group on FLR - Leave Groups.');
  } else {
    let anyClash = false;
    for (const g of groups) {
      const limit = maxOffOf(g);
      const members = ctx.membersByGroup.get(String(g.id)) || new Set();
      const clashes = [];
      for (const { date } of days.days) {
        const others = new Map();
        for (const r2 of ctx.requests) {
          if (r2.id === req.id || !isActive(r2)) continue;
          const s2 = ctx.staffOf(r2);
          if (!s2 || String(s2.id) === String(s.id) || !members.has(String(s2.id))) continue;
          const d2 = ctx.daysOf(r2);
          if (!d2.from || date < d2.from || date > d2.to) continue;
          const status = r2.decision === 'accepted' ? 'accepted' : 'pending';
          const half = d2.days.find((x) => x.date === date && x.amount === 0.5) ? ' (half day)' : '';
          const prev = others.get(String(s2.id));
          if (!prev || (prev.status !== 'accepted' && status === 'accepted')) others.set(String(s2.id), { name: s2.name, status, half });
        }
        const list = [...others.values()];
        const acceptedOthers = list.filter((o) => o.status === 'accepted').length;
        if (1 + list.length > limit) clashes.push({ date, others: list, headcount: 1 + list.length, withAccepted: 1 + acceptedOthers > limit });
      }
      res.groups.push({ id: g.id, name: g.name, limit, rules: g.rules || '', clashes });
      if (clashes.length) {
        anyClash = true;
        res.clashDays += clashes.length;
        if (clashes.some((c) => c.withAccepted)) res.clashWithAccepted = true;
        const shown = clashes.slice(0, 6).map((c) => `${fmtDate(c.date, false)}: ${c.others.map((o) => `${o.name} – ${o.status}${o.half}`).join(', ')}`);
        const more = clashes.length > 6 ? ` …and ${clashes.length - 6} more day(s)` : '';
        lines.push(`Group "${g.name}" (max ${limit} off at once): CLASH on ${plural(clashes.length, 'day')} – ${shown.join('; ')}${more}.`);
      } else {
        lines.push(`Group "${g.name}" (max ${limit} off at once): no clash.`);
      }
      if (g.rules) lines.push(`Group rules: ${g.rules}`);
    }
    res.groupStatus = anyClash ? 'Clash' : 'No clash';
  }
  if (over) { res.suggested = 'Deny'; res.reason = 'not enough allowance left'; }
  else if (startsBeforeTracker) { res.suggested = 'Review'; res.reason = `some dates are before the tracker starts on 1 Jan ${FIRST_LEAVE_YEAR}`; }
  else if (res.groupStatus === 'Clash') {
    res.suggested = 'Review';
    res.reason = res.clashWithAccepted ? 'too many people in the group would be off (clashes with accepted leave)' : 'clashes with other pending requests in the group';
  } else if (res.groupStatus === 'No group set') { res.suggested = 'Review'; res.reason = 'no leave group set, so clashes could not be checked'; }
  else if (days.warnings.length) { res.suggested = 'Review'; res.reason = days.warnings[0].replace(/\.$/, ''); }
  else { res.suggested = 'Accept'; res.reason = 'within allowance and no group clash'; }
  lines.push(`Suggested: ${res.suggested} – ${res.reason}.`);
  res.details = lines.join('\n');
  return res;
}
function whoIsOff(ctx, date, { includePending = true } = {}) {
  const out = [];
  if (isWeekend(date) || ctx.bankHolidays.has(date)) return out;
  for (const r of ctx.requests) {
    if (!(r.decision === 'accepted' || (includePending && isPending(r)))) continue;
    const entry = ctx.daysOf(r).days.find((x) => x.date === date);
    if (entry) out.push({ request: r, staff: ctx.staffOf(r), amount: entry.amount });
  }
  return out;
}

const today = todayInLondon();   // as the page's own "State" section sets it; mapData reads it

function cv(it) { const m = {}; for (const c of it.column_values || []) m[c.id] = c; return m; }
// When monday.com last changed a column: it keeps the moment in the column's value ("changed_at", in UTC).
function changedAt(c) {
  if (!c) return null;
  if (typeof c.updated_at === 'string' && c.updated_at) return c.updated_at;
  try { const v = JSON.parse(c.value || 'null'); return v && typeof v.changed_at === 'string' ? v.changed_at : null; } catch (e) { return null; }
}
function num(c) {
  if (c && typeof c.number === 'number') return c.number;
  const t = ((c && c.text) || '').trim();
  if (!t) return null;
  const n = Number(t);
  return Number.isFinite(n) ? n : null;
}
function lab(c) { const v = c ? (c.label != null ? c.label : c.text) : null; return v && String(v).trim() ? String(v) : null; }
function txt(c) { const v = c ? c.text : null; return v && String(v).trim() ? String(v) : null; }
function links(c) {
  if (c && Array.isArray(c.linked_item_ids)) return c.linked_item_ids.map(String);
  try {
    const p = JSON.parse((c && c.value) || 'null');
    if (p && Array.isArray(p.linkedPulseIds)) return p.linkedPulseIds.map((x) => String(x.linkedPulseId));
  } catch (e) { /* ignore */ }
  return [];
}
function timeline(c) {
  let p = null;
  try { p = JSON.parse((c && c.value) || 'null'); } catch (e) { /* ignore */ }
  return { from: cleanDate(c && c.from) || cleanDate(p && p.from), to: cleanDate(c && c.to) || cleanDate(p && p.to) };
}

function mapData(raw) {
  const requests = raw.items.req.map((it) => {
    const c = cv(it), d = timeline(c[REQ.dates]), staffIds = links(c[REQ.staff]);
    const decidedOn = c[REQ.decidedOn] ? cleanDate(c[REQ.decidedOn].date || c[REQ.decidedOn].text) : null;
    return {
      id: String(it.id), name: it.name || '', employeeName: (txt(c[REQ.employee]) || '').split(',')[0].trim(),
      staffId: staffIds[0] || null, from: d.from, to: d.to, halfDay: halfDayFromLabel(lab(c[REQ.halfDay])),
      decision: decisionFromLabel(lab(c[REQ.decision])), daysOverride: num(c[REQ.override]),
      notes: txt(c[REQ.notes]) || '', createdAt: it.created_at, email: txt(c[REQ.email]),
      imported: /^imported from/i.test(txt(c[REQ.notes]) || ''),   // added from the old leave record, not sent with the form
      cur: {
        suggested: lab(c[REQ.suggested]), allowanceCheck: lab(c[REQ.allowanceCheck]), groupCheck: lab(c[REQ.groupCheck]),
        workingDays: num(c[REQ.workingDays]), leftAfter: num(c[REQ.leftAfter]), leaveGroup: txt(c[REQ.leaveGroup]),
        details: txt(c[REQ.details]), staffIds, decidedOn, managersNote: txt(c[REQ.managersNote]),
        decidedAt: changedAt(c[REQ.decision]),   // when the Decision last changed: when it was accepted, denied or cancelled
      },
    };
  });
  const staff = raw.items.alw.map((it) => {
    const c = cv(it);
    return {
      id: String(it.id), name: it.name || '', groupIds: links(c[ALW.group]), allowance: num(c[ALW.allowance]),
      shutdownReserve: num(c[ALW.shutdown]), carriedOver: num(c[ALW.carried]), takenBefore: null,
      savedBooked: num(c[ALW.booked]), savedPending: num(c[ALW.pending]),
      email: ((c[ALW.email] && (c[ALW.email].email || txt(c[ALW.email]))) || '').trim().toLowerCase() || null,
    };
  });
  const groups = raw.items.grp.map((it) => {
    const c = cv(it);
    return { id: String(it.id), name: it.name || '', memberIds: links(c[GRP.members]), maxOff: num(c[GRP.maxOff]), rules: txt(c[GRP.rules]) || '' };
  });
  const bankHolidays = new Map(), closureTypes = new Map();
  for (const it of raw.items.clo) {
    const c = cv(it);
    const d = c[CLO.date] ? cleanDate(c[CLO.date].date || c[CLO.date].text) : null;
    if (!d) continue;
    const type = lab(c[CLO.type]) || 'Bank holiday';
    bankHolidays.set(d, isCloseDay(type) ? CLOSE_DAY : it.name || 'Bank holiday');   // the name the Diary, Today and checks show
    closureTypes.set(d, type);
  }
  const other = raw.items.oth.map((it) => {
    const c = cv(it), d = timeline(c[OTH.dates]), staffIds = links(c[OTH.staff]);
    const gid = it.group && it.group.id;
    return {
      id: 'o' + it.id, itemId: String(it.id), employeeName: it.name || '', staffId: staffIds[0] || null,
      type: OTHER_GROUP_TYPES[gid] || (it.group && it.group.title) || 'Other leave',
      from: d.from, to: d.to, halfDay: halfDayFromLabel(lab(c[OTH.halfDay])),
      cur: { workingDays: num(c[OTH.workingDays]), staffIds },
    };
  });
  return { requests, staff, groups, bankHolidays, closureTypes, other, today };
}

export { FIRST_LEAVE_YEAR, BOARD_NAMES, todayInLondon, isWeekend, yearOf, fmtDate, fmtRange, fmtNum, plural, normaliseName, isPending, leaveDays, buildContext, balanceFor, whoIsOff, whoIsOffOther, mapData, evaluateRequest };
