// Generated by scripts/speeding_core.py from speeding/index.html: Fleet Management's own report rules (its
// CALC block) and its MOT, tax and service rule (its DUE block), word for word, for the Hub assistant. Don't
// edit this file: change the report, rebuild it with scripts/sync-speeding.py, and this is rebuilt with it.
  // Rules carried over unchanged from the previous version of this report, plus (28 Sep 2026) FleetView's
  // overall driver score as a second review trigger (reviewStatusOf).
  const LOW_MILES = 150;                        // below this, a rate is limited evidence
  const threshold = limit => limit * 1.1 + 2;   // incident threshold: limit + 10% + 2 mph
  const SERIOUS = 20;                           // mph over the limit
  const STATUS = {
    priority: {label:'Priority review', rank:0},
    above:    {label:'Above fleet average', rank:1},
    limited:  {label:'Limited evidence', rank:2},
    within:   {label:'At or below fleet average', rank:3}
  };
  const toIso = d => d && d.length === 10 ? `${d.slice(6)}-${d.slice(3,5)}-${d.slice(0,2)}` : '';

  // Rows and fleet totals for the chosen period: 'all' = the rolling 30 days, or a week index.
  function periodView(report, period){
    const weeks = report.weeks || [];
    const wi = period === 'all' ? -1 : weeks.findIndex(w => w.start === period);
    if (wi < 0) {
      const f = report.fleet;
      const rows = report.drivers.map(r => ({...r}));
      return {rows, flagged:f.flagged, miles:f.miles, o20:f.o20, fvEvents:f.fvEvents, strict:f.strict,
              start:report.periodStart, end:report.periodEnd, label:'Last 30 days', week:null};
    }
    const i = wi, w = weeks[i];
    const rows = report.drivers.map(r => {
      const x = (r.weeks || [])[i] || {mi:0, trips:0, flag:0, o15:0, o20:0};
      const mi = Math.round(x.mi);
      return {...r, mi, trips:x.trips, flag:x.flag, o15:x.o15, o20:x.o20,
              per100: x.mi ? +(x.flag / x.mi * 100).toFixed(1) : 0, fv:null, strict:null};
    });
    const miles = Math.round(report.drivers.reduce((a, r) => a + (((r.weeks||[])[i]||{}).mi || 0), 0));
    return {rows, flagged:rows.reduce((a,r)=>a+r.flag,0), miles, o20:rows.reduce((a,r)=>a+r.o20,0),
            fvEvents:null, strict:null, start:w.start, end:w.end, label:weekLabel(w), week:i};
  }
  function weekLabel(w){
    const d = s => new Date(s+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
    return `${d(w.start)} – ${d(w.end)}${w.partial ? ' (part week)' : ''}`;
  }
  // Same status rule as before: under 150 miles = limited evidence; otherwise compare the
  // driver's rate per 100 miles with the fleet rate (2x or more = priority review).
  function statusOf(r, avg){
    if (r.mi < LOW_MILES) return 'limited';
    if (!(avg > 0)) return 'within';
    if (r.per100 >= avg * 2) return 'priority';
    if (r.per100 > avg) return 'above';
    return 'within';
  }
  // How a driver's rate compares with the fleet rate, worded so it never contradicts the status.
  function vsFleet(r, avg){
    if (!(avg > 0)) return '';
    const x = r.per100 / avg;
    if (x >= 2) return `${(Math.floor(x * 10) / 10).toFixed(1)}× the fleet rate`;
    if (r.per100 > avg) return `${Math.max(1, Math.floor((x - 1) * 100))}% above the fleet rate`;
    if (r.per100 === avg) return 'equal to the fleet rate';
    return `${Math.max(1, Math.floor((1 - x) * 100))}% below the fleet rate`;
  }
  // Second review trigger, agreed 28 Sep 2026: FleetView's own overall driver score, as imported. A driver with
  // enough miles to rate (not limited evidence) whose score is SCORE_GAP or more points below FleetView's fleet
  // average moves up one group: at or below average -> above fleet average, above -> priority review. It never
  // moves anyone down, and a missing score leaves the speeding status as it is.
  const SCORE_GAP = 15;
  const SCORE_UP = {within:'above', above:'priority'};
  const lowScore = (score, fleetScore) => score != null && fleetScore != null && score <= fleetScore - SCORE_GAP;
  function reviewStatusOf(r, avg, fleetScore){
    const st = statusOf(r, avg);
    return lowScore(r.score, fleetScore) && SCORE_UP[st] ? SCORE_UP[st] : st;
  }
  const SORTS = {
    review: (a,b) => STATUS[a.st].rank - STATUS[b.st].rank || b.o20 - a.o20 || b.per100 - a.per100 || b.flag - a.flag,
    flag:   (a,b) => b.flag - a.flag || b.per100 - a.per100,
    per100: (a,b) => b.per100 - a.per100 || b.flag - a.flag,
    o20:    (a,b) => b.o20 - a.o20 || b.o15 - a.o15 || b.flag - a.flag,
    mi:     (a,b) => b.mi - a.mi,
    d:      (a,b) => a.d.localeCompare(b.d, 'en-GB') || a.reg.localeCompare(b.reg)
  };
  

  // MOT, tax and service: what each date on the Monday fleet board shows (agreed with FLR, 2 Oct 2026). The date is
  // looked at first, then Monday's own status, and the first step that applies decides. Nothing on Monday is changed,
  // and nothing here says a vehicle is safe or unsafe: a date that has passed while Monday says something else stays
  // prominent, for someone to check on the board.
  //   1. No date: Exempt if Monday says Exempt; otherwise "No date on the board" (needs checking).
  //   2. A date that can't be read: needs checking.
  //   3. The date has passed: Overdue if Monday says Overdue too (needs action); otherwise
  //      "<MOT | Tax | Service> date overdue by N days — Monday status needs checking" (needs checking).
  //   4. Monday says Overdue but the date hasn't passed: Overdue on the day itself (Monday's tax automation changes the
  //      status that morning); before it, needs checking.
  //   5. Monday says Exempt and the date is still to come: Exempt, also under Coming up within 30 days.
  //   6. Within 30 days: Due in N days, or Due today (Coming up).
  //   7. Otherwise: OK.
  // Green only when the date is more than 30 days away and Monday doesn't say Overdue or Exempt; red only when the date
  // has passed (or is today) and Monday says Overdue too.
  const DUE_SOON = 30;
  const DUE_NAME = {mot:'MOT', tax:'Tax', service:'Service'};
  // A day as the board's date columns give it ("2026-10-02", or with a time after it), or null if it can't be read.
  function dueDay(s){
    const m = /^(\d{4})-(\d{2})-(\d{2})(?:[ T]\d{2}:\d{2}(?::\d{2})?)?$/.exec(String(s == null ? '' : s).trim());
    if (!m || +m[1] < 1900) return null;
    const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3]));
    return d.getUTCFullYear() === +m[1] && d.getUTCMonth() === +m[2] - 1 && d.getUTCDate() === +m[3] ? `${m[1]}-${m[2]}-${m[3]}` : null;
  }
  const dueDaysBetween = (from, to) => Math.round((Date.parse(to + 'T00:00:00Z') - Date.parse(from + 'T00:00:00Z')) / 864e5);
  const dueCount = (n, one, many) => `${n} ${n === 1 ? one : many}`;
  // x: {status, date} as on the board; key: 'mot' | 'tax' | 'service'; today: 'YYYY-MM-DD' (UK); soon: days (30).
  //   kind: 'action' (Needs action) | 'check' (Needs checking) | 'soon' (Coming up) | 'exempt' | 'ok'
  //   cls:  'over' (red) | 'dated' (outlined in red) | 'check' (dashed) | 'soon' (amber) | 'exempt' (grey) | 'ok' (green)
  //   label names the item for lists ("Service date overdue by 87 days — …"); short goes beside the item's name.
  function dueState(x, key, today, soon){
    soon = soon || DUE_SOON;
    const what = DUE_NAME[key] || 'Due';
    const monday = x && x.status != null && String(x.status).trim() ? String(x.status).trim() : null;
    const st = (monday || '').toLowerCase();
    const raw = x && x.date != null ? String(x.date).trim() : '';
    const out = (kind, cls, label, short, extra) => Object.assign({kind, cls, label, short: short || label, days: null, date: null, monday, upcoming: false}, extra || {});
    if (!raw) return st === 'exempt' ? out('exempt', 'exempt', 'Exempt') : out('check', 'check', 'No date on the board', 'No date');
    const date = dueDay(raw);
    if (!date) return out('check', 'check', "Date can't be read — needs checking", "Date can't be read");
    const n = dueDaysBetween(today, date), at = {days: n, date};
    if (n < 0) return st === 'overdue'
      ? out('action', 'over', `Overdue by ${dueCount(-n, 'day', 'days')}`, null, at)
      : out('check', 'dated', `${what} date overdue by ${dueCount(-n, 'day', 'days')} — Monday status needs checking`, `Date overdue by ${dueCount(-n, 'day', 'days')} — Monday status needs checking`, at);
    if (st === 'overdue') return n === 0
      ? out('action', 'over', 'Overdue · due today', null, at)
      : out('check', 'check', 'Monday says Overdue — date not reached, needs checking', null, at);
    if (st === 'exempt') return out('exempt', 'exempt', 'Exempt', null, Object.assign({upcoming: n <= soon}, at));
    if (n <= soon) return out('soon', 'soon', n === 0 ? 'Due today' : `Due in ${dueCount(n, 'day', 'days')}`, null, Object.assign({upcoming: true}, at));
    return out('ok', 'ok', 'OK', null, at);
  }
  

export { LOW_MILES, SERIOUS, STATUS, threshold, periodView, statusOf, vsFleet, SCORE_GAP, lowScore, reviewStatusOf, SORTS, DUE_SOON, DUE_NAME, dueDay, dueState };
