#!/usr/bin/env python3
"""Build annual-leave/leave-core.js: the Annual Leave page's own leave rules, as a module for the Hub assistant.

The assistant answers "how many days have I got left?", "has my holiday been approved?" and "who's off today?" with the
page's own code, cut from the built page itself, never a copy kept by hand. So the two can't disagree: whenever the page
changes, this runs again (sync-leave.py runs it straight after building the page) and the assistant has the new rules.

What's taken, word for word: the leave boards' column ids, the "Leave rules" section (dates, working days, balances,
who is off) and the data mapping (mapData and its helpers). Nothing else: no rendering, no state, no monday.com calls.

Usage: scripts/leave_core.py      (reads annual-leave/index.html, writes annual-leave/leave-core.js)
"""
import os
import sys

HUB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(HUB, 'annual-leave', 'index.html')
OUT = os.path.join(HUB, 'annual-leave', 'leave-core.js')
EXPORTS = ['FIRST_LEAVE_YEAR', 'BOARD_NAMES', 'todayInLondon', 'isWeekend', 'yearOf', 'fmtDate', 'fmtRange', 'fmtNum',
           'plural', 'normaliseName', 'isPending', 'leaveDays', 'buildContext', 'balanceFor', 'whoIsOff', 'whoIsOffOther',
           'mapData', 'evaluateRequest']


def section(page, start, end, what):
    """The text from `start` up to (not including) the comment block that holds `end`."""
    if page.count(start) != 1:
        sys.exit(f'leave_core: the Annual Leave page should have exactly one "{start}" ({what}); update this script')
    i = page.index(start)
    j = page.find(end, i)
    if j < 0:
        sys.exit(f'leave_core: "{end}" not found after {what}; update this script')
    k = page.rfind('/*', i, j)          # back to the start of that comment
    return page[i:k if k > i else j].rstrip() + '\n'


def build(page):
    consts = section(page, 'const BOARDS = {', 'Leave rules', 'the board constants')
    rules = section(page, 'const FIRST_LEAVE_YEAR', '   State\n', 'the leave rules')
    if page.count('function cv(it)') != 1 or page.count('function rebuild()') != 1:
        sys.exit('leave_core: the data mapping (cv … mapData, before rebuild) has moved; update this script')
    mapping = page[page.index('function cv(it)'):page.index('function rebuild()')].rstrip() + '\n'
    for name in EXPORTS:
        if f'function {name}(' not in consts + rules + mapping and f'const {name} ' not in consts + rules + mapping:
            sys.exit(f'leave_core: {name} is no longer in the sections taken from the page; update this script')
    return ('// Generated by scripts/leave_core.py from annual-leave/index.html: the Annual Leave page\'s own leave rules and\n'
            '// data mapping, word for word, for the Hub assistant. Don\'t edit this file: change the page (the leave tool),\n'
            '// rebuild it with scripts/sync-leave.py, and this is rebuilt with it.\n'
            + consts + '\n' + rules + '\n'
            + 'const today = todayInLondon();   // as the page\'s own "State" section sets it; mapData reads it\n\n'
            + mapping + '\nexport { ' + ', '.join(EXPORTS) + ' };\n')


def main():
    page = open(PAGE, encoding='utf-8').read()
    out = build(page)
    open(OUT, 'w', encoding='utf-8').write(out)
    print(f'annual-leave/leave-core.js updated: the page\'s leave rules, {len(out):,} bytes')


if __name__ == '__main__':
    main()
