#!/usr/bin/env python3
"""Build speeding/speeding-core.js: Fleet Management's own report rules, as a module for the Hub assistant.

The assistant answers "how is Faye's driving?" and "who needs reviewing?" with the report page's own rules (the status
of each driver, the review order, how a rate compares with the fleet's), cut from the built page itself: the block
between /*CALC-START*/ and /*CALC-END*/, word for word. So the two can't disagree: whenever the page changes, this runs
again (sync-speeding.py runs it straight after building the page) and the assistant has the new rules.

Usage: scripts/speeding_core.py      (reads speeding/index.html, writes speeding/speeding-core.js)
"""
import os
import sys

HUB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(HUB, 'speeding', 'index.html')
OUT = os.path.join(HUB, 'speeding', 'speeding-core.js')
EXPORTS = ['LOW_MILES', 'SERIOUS', 'STATUS', 'threshold', 'periodView', 'statusOf', 'vsFleet', 'SCORE_GAP', 'lowScore',
           'reviewStatusOf', 'SORTS']


def build(page):
    start, end = '/*CALC-START*/', '/*CALC-END*/'
    if page.count(start) != 1 or page.count(end) != 1:
        sys.exit('speeding_core: the report page should have one /*CALC-START*/ … /*CALC-END*/ block; update this script')
    block = page[page.index(start) + len(start):page.index(end)]
    for name in EXPORTS:
        if f'const {name} ' not in block and f'function {name}(' not in block:
            sys.exit(f'speeding_core: {name} is no longer in the report\'s CALC block; update this script')
    return ('// Generated by scripts/speeding_core.py from speeding/index.html: Fleet Management\'s own report rules (its\n'
            '// CALC block), word for word, for the Hub assistant. Don\'t edit this file: change the report, rebuild it with\n'
            '// scripts/sync-speeding.py, and this is rebuilt with it.\n'
            + block.strip('\n') + '\n\nexport { ' + ', '.join(EXPORTS) + ' };\n')


def main():
    out = build(open(PAGE, encoding='utf-8').read())
    open(OUT, 'w', encoding='utf-8').write(out)
    print(f'speeding/speeding-core.js updated: the report\'s rules, {len(out):,} bytes')


if __name__ == '__main__':
    main()
