#!/usr/bin/env python3
"""Build speeding/speeding-core.js: Fleet Management's own report rules, as a module for the Hub assistant.

The assistant answers "how is Faye's driving?" and "who needs reviewing?" with the report page's own rules (the status
of each driver, the review order, how a rate compares with the fleet's), cut from the built page itself: the block
between /*CALC-START*/ and /*CALC-END*/, word for word. "When is the MOT due on K8 FLR?" uses the page's MOT, tax and
service rule the same way: the block between /*DUE-START*/ and /*DUE-END*/. So the two can't disagree: whenever the
page changes, this runs again (sync-speeding.py runs it straight after building the page) and the assistant has the
new rules. scripts/due-rule-test.mjs checks the MOT, tax and service rule against the cases agreed with FLR.

Usage: scripts/speeding_core.py      (reads speeding/index.html, writes speeding/speeding-core.js)
"""
import os
import sys

HUB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(HUB, 'speeding', 'index.html')
OUT = os.path.join(HUB, 'speeding', 'speeding-core.js')
EXPORTS = ['LOW_MILES', 'SERIOUS', 'STATUS', 'threshold', 'periodView', 'statusOf', 'vsFleet', 'SCORE_GAP', 'lowScore',
           'reviewStatusOf', 'SORTS']
DUE_EXPORTS = ['DUE_SOON', 'DUE_NAME', 'dueDay', 'dueState']


def cut(page, name, exports):
    start, end = f'/*{name}-START*/', f'/*{name}-END*/'
    if page.count(start) != 1 or page.count(end) != 1:
        sys.exit(f'speeding_core: the report page should have one {start} … {end} block; update this script')
    block = page[page.index(start) + len(start):page.index(end)]
    for n in exports:
        if f'const {n} ' not in block and f'function {n}(' not in block:
            sys.exit(f'speeding_core: {n} is no longer in the report\'s {name} block; update this script')
    return block.strip('\n')


def build(page):
    return ('// Generated by scripts/speeding_core.py from speeding/index.html: Fleet Management\'s own report rules (its\n'
            '// CALC block) and its MOT, tax and service rule (its DUE block), word for word, for the Hub assistant. Don\'t\n'
            '// edit this file: change the report, rebuild it with scripts/sync-speeding.py, and this is rebuilt with it.\n'
            + cut(page, 'CALC', EXPORTS) + '\n\n' + cut(page, 'DUE', DUE_EXPORTS)
            + '\n\nexport { ' + ', '.join(EXPORTS + DUE_EXPORTS) + ' };\n')


def main():
    out = build(open(PAGE, encoding='utf-8').read())
    open(OUT, 'w', encoding='utf-8').write(out)
    print(f'speeding/speeding-core.js updated: the report\'s rules, {len(out):,} bytes')


if __name__ == '__main__':
    main()
